<?php

/**
 * @file
 * Module for locking features/components.
 */

/**
 * Implements hook_kw_manifests_info().
 */
function feature_lock_kw_manifests_info() {
  return array(
    'features_lock_components' => array(
      'callback' => 'feature_lock_main_lock_features',
      'dependencies' => array(
        array(
          'module' => 'drop_ship',
          'name' => 'features_revert',
        )
      )
    ),
  );
}

/**
 * Lock features, components, and particular components of features.
 */
function feature_lock_main_lock_features() {
  // Get all locks provided by hook_lock_features().
  $all_locks = module_invoke_all('lock_feature');
  feature_lock_lock_features($all_locks);
}

/**
 * Set the lock attribute on a features component or feature.
 *
 * You can set a lock on all components across all features, a full features
 *   module, or a single component of a feature.
 *
 * @param array $locks
 *   An array that is structured:
 *   array(
 *     'components' => array('global_component1', 'global_component2'),
 *     'features' => array('name_of_features_module1', 'features_module2'),
 *     'components_of_feature' => array(
 *       'name_of_features_module3' => array(
 *         'component1'=>TRUE,
 *         'component2'=>TRUE,
 *       )
 *     )
 *   )
 */
function feature_lock_lock_features($locks) {
  // Get defaul values.
  $feature_locked =  variable_get('features_feature_locked', array());
  $lock_f = $lock_c = array();

  foreach ($locks as $type => $value) {
    switch ($type) {
      // Lock components.
      case 'components':
        foreach ($value as $component) {
          if (is_string($component)) {
            variable_set($component, TRUE);
          }
        }
        break;
      // Get features that should be locked.
      case 'features':
        if (is_array($value) && count($value)) {
          foreach ($value as $feature) {
            $lock_f[$feature] = array('_all' => TRUE);
          }
        }
        break;
      // Get components of feature that should be locked.
      case 'components_of_feature':
        $lock_c =  is_array($value) && count($value) ? $value : array();
        break;
    }
  }

  // Lock features and components of feaures.
  if (count($lock_f + $lock_c)) {
    // Merge new values.
    $new_feature_locked = array_merge_recursive($lock_f,  $lock_c);
    // Merge default values.
    $feature_locked = array_merge($feature_locked, $new_feature_locked);
    variable_set('features_feature_locked', $feature_locked);
  }
}
